flags: {}
extra-package-dbs: []
packages:
- '.'
setup-info:
  ghc:
    linux64:
      8.0.0.20160421:
        url: https://downloads.haskell.org/~ghc/8.0.1-rc4/ghc-8.0.0.20160421-x86_64-deb8-linux.tar.xz
        sha1: 6e8bd7c96fa46da0b8c12bf9d62f006940adfe67
    macosx:
      8.0.0.20160421:
        url: https://downloads.haskell.org/~ghc/8.0.1-rc4/ghc-8.0.0.20160421-x86_64-apple-darwin.tar.xz
        sha1: f1b60c26bd29f48e03f0881034bcaaa3d53b925f
extra-deps:
- HUnit-1.3.1.1
- QuickCheck-2.8.2
- aeson-0.11.1.4
- aeson-pretty-0.7.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- attoparsec-0.13.0.2
- base-compat-0.9.1
- cmdargs-0.10.14
- cpphs-1.20.1
- crackNum-1.5
- data-binary-ieee754-0.4.4
- dlist-0.7.1.2
- fail-4.9.0.0
- hashable-1.2.4.0
- haskell-lexer-1.0
- haskell-src-exts-1.17.1
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- ieee754-0.7.8
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.12.1.0
- polyparse-1.12
- pretty-show-1.6.9
- primitive-0.6.1.0
- quickcheck-io-0.1.2
- random-1.1
- sbv-5.12
- scientific-0.3.4.6
- setenv-0.1.1.3
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.4
- text-1.2.2.1
- tf-random-0.5
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.0
- vector-0.11.0.0
resolver: lts-7.24
